### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(HelicopterContent)
add_subdirectory(Helicopter)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_Roadplugin
    Generated_QtQuick3D_Attack_helicopter_conceptplugin
    Generated_QtQuick3D_Tron_chopper_sketchfabplugin
    HelicopterContentplugin
    Helicopterplugin)